# Generated by Django 5.0 on 2023-12-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0002_league_s2_league_sw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statcard',
            name='afg',
            field=models.FloatField(blank=True, null=True, verbose_name='AFG%'),
        ),
        migrations.AlterField(
            model_name='statcard',
            name='ato',
            field=models.FloatField(blank=True, null=True, verbose_name='A/TO'),
        ),
        migrations.AlterField(
            model_name='statcard',
            name='ft_per',
            field=models.FloatField(blank=True, null=True, verbose_name='FT%'),
        ),
    ]
